### ISSUE TITLE
mixin grid-column "$pull: false" not working?

### ISSUE THREAD

**Issue by shrwnsan** [milohuang/reverie#177]
Let's say you have the following markup:

``` html
<section class="container row" role="document">
    <div role="main">lorem...</div>
</section
```

Before, `<div role="main">` was `<div role="main" class="small-12 large-6 large-offset-6 pull-6">` but I wanted more control at a larger screen size so I took the classes out. E.g. `large-9 large-centered`

Here's my SCSS:

``` css
div[role=main] {
    @include grid-column(
        // small-12
        $columns: 12
    );
}
@media #{$small} {
    div[role=main] {
        @include grid-column(
            $columns: 6,
            $last-column: true,
            $offset: 6,
            $pull: 6
        );
    }
}
@media only screen and (min-width: emCalc(1024px)) {
    div[role=main] {
        @include grid-column(
            $columns: 9,
            $center: true,
            $offset: false,
            $pull: false
        );
    }
}
```

It seems that the `right: 50%` style-rule from `$offset: 6` ain't getting overwritten. Can anyone else replicated the behavior?

I had to add this to the last media query: `right: auto;`

``` scss
@media only screen and (min-width: emCalc(1024px)) {
    div[role=main] {
        @include grid-column(...);
        right: auto;
    }
}
```

I'm on the latest commit from upstream/master of reverie... Problem from the actual Foundation branch eh?

Tips greatly appreciated. TIA
