### ISSUE TITLE
Missing form.css style declarations in foundation.css

### ISSUE THREAD

**Issue by micjamking** [milohuang/reverie#28]
Sorry to bring this up again, but in the process of making a pull request to Foundation for the sidebar input width bug, I noticed your foundation.css is missing a style declaration that is present in forms.css that may solve the issue:

_Line 35 of forms.css_

``` css
    input.expand, textarea.expand { width: 100%; }
```

_Line 41 of forms.css_

``` css
    textarea.locked.expand  { max-width: 100%; }
```

I'm not sure if you left these out intentionally, but this gets rid of the bug in the Foundation framework demo (test.html, although I had to manually add the input field to the sidebar).
